# application.properties - ms-usuarios
# Configuración del Microservicio de Usuarios y Control de Accesos para BookPoint Chile
# Arquitecto de Software: Antigravity

# Puerto del Servidor local
server.port=8083

# Nombre del Microservicio en Spring Boot
spring.application.name=ms-usuarios

# Configuración de Base de Datos MySQL (Esquema: bookpoint_usuarios)
spring.datasource.url=jdbc:mysql://localhost:3306/bookpoint_usuarios?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Registro y Descubrimiento Eureka (Desactivado temporalmente para pruebas locales)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

# Habilitar logging del nivel INFO para trazabilidad de creación de cuentas e intentos fallidos
logging.level.cl.bookpointchile.usuarios=INFO
